name: Check and test the source code
on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main
jobs:
 hello-tomato:
  name: output hello tomato
  # CI上の仮装の環境が必要なので必須
  runs-on: ubuntu-latest
  steps:
   - name: test hello tomato
     run: echo hello tomato