name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use secret key
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: echo "Using API key ${{ env.API_KEY }}"
